name: Build Marauder for Heltec V3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ESP32Marauder (código oficial)
        uses: actions/checkout@v4
        with:
          repository: justcallmekoko/ESP32Marauder
          ref: master

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar PlatformIO
        run: pip install platformio

      - name: Compilar firmware (Heltec V3)
        working-directory: esp32_marauder
        run: pio run -e heltec_wifi_lora_32_V3

      - name: Publicar arquivo .bin
        uses: actions/upload-artifact@v4
        with:
          name: heltec-v3-marauder-firmware
          path: esp32_marauder/.pio/build/heltec_wifi_lora_32_V3/firmware.bin
